 services:
  - type: web
    name: news-generator
    env: node
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ARK_API_KEY
        value: ac3f27b4-8b16-407c-8686-babd1eaf0adc
        sync: false